fix free heap output
Open-Smartwatch/open-smartwatch-os pull request #134
Opened 2021-07-21 13:57 UTC by uvwxy

@Simonmicro 

Does this make sense?

2021-07-21 13:58 UTC, uvwxy commented
Output on the GPS Edition:

```
========= Memory Monitor =========
core 0 (high):  788B of 4096B
core 1 (high):  5168B of 8192B
heap (high):    223276B of 4477336B
heap (curr):    4378132B of 4477336B
========= Memory Monitor =========
core 0 (high):  788B of 4096B
core 1 (high):  5168B of 8192B
heap (high):    223540B of 4477336B
heap (curr):    4378132B of 4477336B
```


Output on the Light Edition:

```
========= Memory Monitor =========
core 0 (high):  636B of 4096B
core 1 (high):  1628B of 8192B
heap (high):    221976B of 307696B
heap (curr):    160084B of 307696B
========= Memory Monitor =========
core 0 (high):  760B of 4096B
core 1 (high):  1628B of 8192B
heap (high):    221976B of 307696B
heap (curr):    160084B of 307696B
```

2021-07-28 07:30 UTC, Simonmicro requested changes

2021-07-28 07:30 UTC, Simonmicro commented on src/services/OswServiceTaskMemMonitor.cpp
> +  Serial.print((ESP.getHeapSize() + ESP.getPsramSize()) - this->heapHigh);
It seems to be... Not correct - the high value should always be higher than the current (or at least equal).

Take a look here for the high-watermakrs: https://github.com/espressif/arduino-esp32/blob/5458df0a5435db0914d24770865a93e6d35bdab3/cores/esp32/Esp.h#L73

I guess we have to add an `getMinFreePsram()` to https://github.com/Open-Smartwatch/open-smartwatch-os/blob/d0f2a1f4d56091eebabf36c3bef450ad44b1af87/src/services/OswServiceTaskMemMonitor.cpp#L14

2021-07-28 07:31 UTC, Simonmicro commented
I'll take a look into this the next days - feel free to ping me when you have further ideas.

2021-08-10 18:51 UTC, closed without merging