Ci : introduce threading
Open-Smartwatch/open-smartwatch-os pull request #219
Opened 2022-04-17 18:46 UTC by RuffaloLavoisier

We want to reduce OSW all-model compile running time.

2022-04-17 19:44 UTC, uvwxy commented
Does this improve buildtime on github? Or just locally? My expectation would be this only improves local builds. Would be positively surprise if this also would speed CI builds.

Lgtm though :)
> On 17. Apr 2022, at 20:46, RuffaloLavoisier ***@***.***> wrote:
> 
> ﻿
> We want to reduce OSW all-model compile running time.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Open-Smartwatch/open-smartwatch-os/pull/219
> 
> Commit Summary
> 
> b025d05 Ci : introduce threading
> File Changes  (1 file)
> M .github/buildEverything.py (22)
> Patch Links:
> 
> https://github.com/Open-Smartwatch/open-smartwatch-os/pull/219.patch
> https://github.com/Open-Smartwatch/open-smartwatch-os/pull/219.diff
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

2022-04-17 23:23 UTC, RuffaloLavoisier commented
@uvwxy 
Expectations are that CI build speeds will be improved.

2022-04-18 13:49 UTC, simonmicro commented
I think this will also improve build times on GitHub... BUT:

- As far as I recall the `pio` command already uses more than one thread... Right? What is the default of `-j`? At least on my PC it is already blazingly fast...
- To retrieve the cpu thread count, please take a look [here](https://stackoverflow.com/a/68285053/11664229) - so we are not additional platform-depended on `nproc`...

2022-04-18 13:53 UTC, RuffaloLavoisier commented
I added the platformio compile job because the way I was doing plan it doesn't seem to work with Github. (Lets find out more...) Now it seems that the time to build all models will be shorter than before.

2022-04-18 13:57 UTC, RuffaloLavoisier commented
> * my PC it is already blazingly fast

:+1: 
@simonmicro 
But this is the Github CI system.

2022-04-18 14:01 UTC, RuffaloLavoisier commented
>What is the default of `-j`?

Control a number of parallel build jobs. Default is a number of CPUs in a system.
See https://docs.platformio.org/en/latest//core/userguide/cmd_run.html#cmdoption-pio-run-j

wait...does this mean the number of CPUs? Does that mean parallel work?

2022-04-20 08:06 UTC, simonmicro requested changes

2022-04-20 08:06 UTC, simonmicro commented on .github/buildEverything.py
> +            job_number = str(os.cpu_count() * 2)
The hyper-threads are already counted into that number!

2022-04-20 08:14 UTC, simonmicro commented
> Default is a number of CPUs in a system

And I don't see any advantage of explicitly setting the CPU core count using `-j`...

2022-04-20 08:37 UTC, closed without merging

2022-04-23 01:17 UTC, RuffaloLavoisier commented
Eureka... I think I found a way. I'll open up PR again.

2022-04-23 02:37 UTC, RuffaloLavoisier commented
See #221

2022-04-25 04:11 UTC, RuffaloLavoisier commented
In my humble opnion, I recommend working with one history or article. That way, we can check the previous changes and issues so you don're not confused. This PR has been disabled because a new PR was accidentally opened. I apologize.