CI: add check-build for emulator
Open-Smartwatch/open-smartwatch-os pull request #285
Opened 2022-08-19 09:05 UTC by RuffaloLavoisier

It's a draft.

2022-08-27 12:50 UTC, simonmicro requested changes

2022-08-27 12:50 UTC, simonmicro commented on .github/workflows/test-emulator.yml
> +    - name: Cache pip
Not used - the emulator is on C++

2022-08-27 12:50 UTC, simonmicro commented on .github/workflows/test-emulator.yml
> +    - name: Cache PlatformIO
And the emulator does not use PlatformIO

2022-08-27 12:50 UTC, simonmicro commented on .github/workflows/test-emulator.yml
> +    - name: Install swig
The emulator does not support LUA (currently?)

2022-08-27 12:51 UTC, simonmicro commented
You write it is a draft -> please mark it as such!

2022-08-27 14:11 UTC, RuffaloLavoisier reviewed
@simonmicro LGTM

2022-09-03 22:47 UTC, simonmicro commented
Superseeded by #289 289

2022-09-03 22:47 UTC, closed without merging