Add web interface virtual mode
Open-Smartwatch/open-smartwatch-os pull request #287
Opened 2022-08-25 07:13 UTC by RuffaloLavoisier

Add Web-interface window.

2022-08-25 07:22 UTC, RuffaloLavoisier reviewed
As a result, basically, LGTM

2022-08-27 11:44 UTC, simonmicro requested changes

2022-08-27 11:44 UTC, simonmicro commented on emulator/src/Emulator.cpp
> -    this->mainWindow = SDL_CreateWindow("OSW-OS Emulator", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, DISP_W + this->guiPadding + this->guiWidth + this->guiPadding, DISP_H, SDL_WINDOW_RESIZABLE
Please revert this. This was intended

2022-08-27 11:44 UTC, simonmicro commented on emulator/src/Emulator.cpp
> +void OswEmulator::drawWatchOverlay() {
What is this doing?

2022-08-27 11:44 UTC, simonmicro commented on emulator/src/Emulator.cpp
> +        // drawWatchOverlay();
And its commented!?

2022-08-27 11:44 UTC, simonmicro commented on emulator/src/Emulator.cpp
> +char* OswEmulator::convertDateformat(int emulatorWebInterfaceDateFormat) {
Didn't we just added this? We may be able to strip that after the rebase

2022-08-27 11:44 UTC, simonmicro commented on emulator/include/Emulator.hpp
> +    void* keyList[25] = {
This makes extension pretty hard... Why?

2022-08-27 11:46 UTC, simonmicro commented on emulator/include/Emulator.hpp
> +    void* keyList[25] = {
It draws an overlay, which shows a display border... We should do that in SDL directly - as this is a job of the emulator.

2022-08-27 11:47 UTC, simonmicro commented on emulator/src/Emulator.cpp
> -    this->mainWindow = SDL_CreateWindow("OSW-OS Emulator", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, DISP_W + this->guiPadding + this->guiWidth + this->guiPadding, DISP_H, SDL_WINDOW_RESIZABLE
It draws an overlay, which shows a display border... We should do that in SDL directly - as this is a job of the emulator.

2022-09-06 16:05 UTC, simonmicro approved these changes

2022-09-06 22:24 UTC, merged