CI: skip unnecessary actions
Open-Smartwatch/open-smartwatch-os pull request #313
Opened 2022-10-16 10:42 UTC by RuffaloLavoisier

PR for branches at the same storage level takes a lot of time to check with one push and one PR. I think we can reduce this in this way.

2022-10-16 14:16 UTC, RuffaloLavoisier commented
I've improved this. https://github.com/Open-Smartwatch/open-smartwatch-os/pull/301

2022-10-16 14:28 UTC, RuffaloLavoisier commented
LGTM

2022-10-18 11:23 UTC, simonmicro approved these changes

2022-10-18 11:23 UTC, simonmicro commented on .github/workflows/test-EMULATOR.yml
> +    paths_ignore: '["**/*.md", "**/scripts/screen_capture/**"]'
I think the screen capture path is somewhat very specific - but I have no idea to make it better :)

2022-10-18 11:26 UTC, simonmicro requested changes

2022-10-18 11:26 UTC, simonmicro commented on .github/workflows/test-EMULATOR.yml
> +        uses: fkirc/skip-duplicate-actions@master
Do not use master here - please pin it to a specific version number or even commit hash instead!

2022-10-18 14:12 UTC, merged