Bug/gif bg flag
Open-Smartwatch/open-smartwatch-os pull request #363
Opened 2023-04-14 22:33 UTC by simonmicro

Fixes #362 

I also needed to redesign the workflows to work with multiple flags defined at the same time, as the build-script was not proper cleaning all defines before (which caused size-problems with the `GIF_BG` flag). After changing that, too many flags were removed, so I re-engineered the flag-extraction from the docs to just contain all required ones.

2023-04-19 15:04 UTC, simonmicro commented on .github/getWorkflowMatrix.py
> +                if match := re.match(r'^`(.+)` \| .+ \| (.+)$', line):
Fair point, will fix that.

2023-04-19 15:09 UTC, simonmicro commented
Here your go @RuffaloLavoisier :wink:

2023-04-19 15:16 UTC, RuffaloLavoisier requested changes
check it one.

2023-04-19 15:16 UTC, RuffaloLavoisier commented on .github/getWorkflowMatrix.py
> +                    break
how about
```
for file in os.listdir(langBasePath):
      if !file.endswith('.h'): continue
      defaultFile = langBasePath + file
      break
```

2023-04-22 10:43 UTC, simonmicro commented
@RuffaloLavoisier I have to admit, that I'm no real fan of concatenating `if ...: continue` statements into one-liners. Their existence have a severe impact onto the code execution flow and should not (especially if they are not the first statement) be hidden under the rest of the logic. On the other hand, I do not think that they are that important to justify multiple empty new lines before and after or own comments to highlight them again if they are concatenated.

2023-04-22 10:45 UTC, simonmicro commented on .github/getWorkflowMatrix.py
> +                    break
Yes, this could be a one-liner, but why? It would make reading very hard... Or am I wrong about that?

2023-04-22 13:19 UTC, RuffaloLavoisier commented on .github/getWorkflowMatrix.py
> +                    break
This is just to cause problems that slow down reading and fill the screen when there is a lot of indentation of code. Never mind, there's no answer :)

2023-04-22 13:31 UTC, RuffaloLavoisier approved these changes
Looks Good To Me - 👍

2023-04-22 13:31 UTC, merged