Refactoring code chunk
Open-Smartwatch/open-smartwatch-os pull request #400
Opened 2024-09-14 14:54 UTC by RuffaloLavoisier

with #399

2024-09-15 11:38 UTC, simonmicro requested changes
Some good changes, some... Why?

2024-09-15 11:38 UTC, simonmicro commented on src/apps/tools/OswAppDistStats.cpp
> +
I do not think define-ing the number of week days is really that useful - especially as this define is never reuzsed and just re-defined in each source file. If you really want to label it (and I stretch: I you _really_ want to), maybe declare a `constexpr` int before the `for` call and avoid using the pre-processor for this.

2024-09-15 11:38 UTC, simonmicro commented on src/apps/watchfaces/OswAppWatchface.cpp
> +    uint8_t index = 0;
Why did you move this out of the `for`-loop if you are not accessing it outside the loop? Just leave it in there to reduce the potential of variable-name collisions.

2024-09-15 11:38 UTC, simonmicro commented on src/apps/watchfaces/OswAppWatchface.cpp
> +        hal->gfx()->setTextCursor(CENTER_X, 221);
I would not hard-code such value! The display size is dynamic and the placement of the boxes is too. If you want you could try to tell the compiler to pre-calculate it using a `constexpr`, but this math is really not a slowdown.

2024-09-15 11:38 UTC, simonmicro commented on src/apps/watchfaces/OswAppWatchfaceMix.cpp
>      hal->getLocalTime(&hour, &minute, &second);
Removed it before, but here... Not?

2024-09-28 08:16 UTC, RuffaloLavoisier commented
LGTM.

2024-09-29 02:44 UTC, RuffaloLavoisier commented
to #405.

2024-09-29 02:44 UTC, closed without merging